### ISSUE TITLE
关于您的论文在CONVO1和CONVO2结合时与代码有所不同的问题

### ISSUE THREAD

**Issue by zeroRains** [zh460045050/SNL_ICCV2021#1]
您好在阅读您的论文时，原文关于CONVO1和CONVO2结合的过程中使用的是加法，如下图
![U %69B6KQCDQ}WBVK$IMMQ9](https://user-images.githubusercontent.com/73021377/133010924-ba593406-3616-4c8d-9662-b4487136166d.jpg)

但是在阅读代码的时候发现，您在结合CONVO1和CONVO2的时候使用的是减法，请问这是为什么呢？
[https://github.com/zh460045050/SNL_ICCV2021/blob/4d4a7af2bab9991d10c0df8d632753bc913daeb1/SNL-MMSeg/snl_head.py#L214
](https://github.com/zh460045050/SNL_ICCV2021/blob/4d4a7af2bab9991d10c0df8d632753bc913daeb1/SNL-MMSeg/snl_head.py#L214)

**Comment by zh460045050** [comment]
实际上SNL加号与减号的区别就是学习的是θ^_{1}还是θ_{1}，这两者理论上其实是一致的。相关部分主要是论文公式10和公式11：从公式10实际推导中得到的公式其实是带负号的也就是：F(A,Z)=θ^_{0}Z + θ^_{1} (-A) Z +\sum_{θ^_{k} (-A)^{k} Z}$，但由于θ^是不是一个特定值而是一个可学习的参数，所以在公式11为了简洁我们将负号和θ^结合在一起看成一个新的参数θ也就是，θ_{k}=(-1)^{k}*θ^。

**Comment by zeroRains** [comment]
明白了，谢谢您
